// Movie
export const GET_MOVIE = "GET_MOVIE";
export const FILTER_MOVIE = "FILTER_MOVIE";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const GET_MOVIE_BY_ID_SUCCESS = "GET_MOVIE_BY_ID_SUCCESS";
export const SELECTED_MOVIE = "SELECTED_MOVIE";
export const SELECTED_MOVIE_TIMING = "SELECTED_MOVIE_TIMING";
export const MOVIE_SEAT_COUNT = "MOVIE_SEAT_COUNT";
export const THEATRE_LAYOUT = "THEATRE_LAYOUT";
export const THEATRE_LAYOUT_SUCCESS = "THEATRE_LAYOUT_SUCCESS";
export const UPDATE_SEAT_PREFRENCE = "UPDATE_SEAT_PREFRENCE";
export const RESET_SEAT_SELECTION = "RESET_SEAT_SELECTION";
// common
export const IS_LOADING = "IS_LOADING";
export const API_FAILURE = "API_FAILURE";
